; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -fast-isel < %s | FileCheck -check-prefixes=CHECK,FASTISEL %s
; RUN: llc < %s | FileCheck -check-prefixes=CHECK,SDAG %s

target datalayout = "e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-windows-msvc"

define void @issue56055(ptr addrspace(270) %ptr, ptr %out) {
; FASTISEL-LABEL: issue56055:
; FASTISEL:       # %bb.0:
; FASTISEL-NEXT:    addl $2, %ecx
; FASTISEL-NEXT:    movl %ecx, (%rdx)
; FASTISEL-NEXT:    retq
;
; SDAG-LABEL: issue56055:
; SDAG:       # %bb.0:
; SDAG-NEXT:    # kill: def $ecx killed $ecx def $rcx
; SDAG-NEXT:    leal 2(%rcx), %eax
; SDAG-NEXT:    movl %eax, (%rdx)
; SDAG-NEXT:    retq
  %add.ptr = getelementptr inbounds i8, ptr addrspace(270) %ptr, i32 2
  store ptr addrspace(270) %add.ptr, ptr %out
  ret void
}

define void @issue56055_vector(<2 x ptr addrspace(270)> %ptr, ptr %out) {
; CHECK-LABEL: issue56055_vector:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movdqa (%rcx), %xmm0
; CHECK-NEXT:    movdqa {{.*#+}} xmm1 = [2,2,u,u]
; CHECK-NEXT:    paddd %xmm0, %xmm1
; CHECK-NEXT:    movq %xmm1, (%rdx)
; CHECK-NEXT:    retq
  %add.ptr = getelementptr inbounds i8, <2 x ptr addrspace(270)> %ptr, <2 x i32> <i32 2, i32 2>
  store <2 x ptr addrspace(270)> %add.ptr, ptr %out
  ret void
}

define void @issue56055_small_idx(ptr addrspace(270) %ptr, ptr %out, i16 %idx) {
; FASTISEL-LABEL: issue56055_small_idx:
; FASTISEL:       # %bb.0:
; FASTISEL-NEXT:    movswl %r8w, %eax
; FASTISEL-NEXT:    addl %eax, %ecx
; FASTISEL-NEXT:    movl %ecx, (%rdx)
; FASTISEL-NEXT:    retq
;
; SDAG-LABEL: issue56055_small_idx:
; SDAG:       # %bb.0:
; SDAG-NEXT:    movswl %r8w, %eax
; SDAG-NEXT:    addl %ecx, %eax
; SDAG-NEXT:    movl %eax, (%rdx)
; SDAG-NEXT:    retq
  %add.ptr = getelementptr inbounds i8, ptr addrspace(270) %ptr, i16 %idx
  store ptr addrspace(270) %add.ptr, ptr %out
  ret void
}

define void @issue56055_small_idx_vector(<2 x ptr addrspace(270)> %ptr, ptr %out, <2 x i16> %idx) {
; FASTISEL-LABEL: issue56055_small_idx_vector:
; FASTISEL:       # %bb.0:
; FASTISEL-NEXT:    pshuflw {{.*#+}} xmm0 = mem[0,0,2,1,4,5,6,7]
; FASTISEL-NEXT:    psrad $16, %xmm0
; FASTISEL-NEXT:    paddd (%rcx), %xmm0
; FASTISEL-NEXT:    movq %xmm0, (%rdx)
; FASTISEL-NEXT:    retq
;
; SDAG-LABEL: issue56055_small_idx_vector:
; SDAG:       # %bb.0:
; SDAG-NEXT:    pshuflw {{.*#+}} xmm0 = mem[0,0,2,1,4,5,6,7]
; SDAG-NEXT:    psrad $16, %xmm0
; SDAG-NEXT:    movdqa (%rcx), %xmm1
; SDAG-NEXT:    paddd %xmm0, %xmm1
; SDAG-NEXT:    movq %xmm1, (%rdx)
; SDAG-NEXT:    retq
  %add.ptr = getelementptr inbounds i8, <2 x ptr addrspace(270)> %ptr, <2 x i16> %idx
  store <2 x ptr addrspace(270)> %add.ptr, ptr %out
  ret void
}

define void @issue56055_large_idx(ptr addrspace(270) %ptr, ptr %out, i64 %idx) {
; FASTISEL-LABEL: issue56055_large_idx:
; FASTISEL:       # %bb.0:
; FASTISEL-NEXT:    addl %r8d, %ecx
; FASTISEL-NEXT:    movl %ecx, (%rdx)
; FASTISEL-NEXT:    retq
;
; SDAG-LABEL: issue56055_large_idx:
; SDAG:       # %bb.0:
; SDAG-NEXT:    # kill: def $ecx killed $ecx def $rcx
; SDAG-NEXT:    leal (%r8,%rcx), %eax
; SDAG-NEXT:    movl %eax, (%rdx)
; SDAG-NEXT:    retq
  %add.ptr = getelementptr inbounds i8, ptr addrspace(270) %ptr, i64 %idx
  store ptr addrspace(270) %add.ptr, ptr %out
  ret void
}

define void @issue56055_large_idx_vector(<2 x ptr addrspace(270)> %ptr, ptr %out, <2 x i64> %idx) {
; FASTISEL-LABEL: issue56055_large_idx_vector:
; FASTISEL:       # %bb.0:
; FASTISEL-NEXT:    pshufd {{.*#+}} xmm0 = mem[0,2,2,3]
; FASTISEL-NEXT:    paddd (%rcx), %xmm0
; FASTISEL-NEXT:    movq %xmm0, (%rdx)
; FASTISEL-NEXT:    retq
;
; SDAG-LABEL: issue56055_large_idx_vector:
; SDAG:       # %bb.0:
; SDAG-NEXT:    pshufd {{.*#+}} xmm0 = mem[0,2,2,3]
; SDAG-NEXT:    movdqa (%rcx), %xmm1
; SDAG-NEXT:    paddd %xmm0, %xmm1
; SDAG-NEXT:    movq %xmm1, (%rdx)
; SDAG-NEXT:    retq
  %add.ptr = getelementptr inbounds i8, <2 x ptr addrspace(270)> %ptr, <2 x i64> %idx
  store <2 x ptr addrspace(270)> %add.ptr, ptr %out
  ret void
}

