; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu | FileCheck %s

define i1000 @square(i1000 %A) nounwind {
; CHECK-LABEL: square:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    movq %rsi, %r13
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rbx
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %r14
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %r12
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rax
; CHECK-NEXT:    bswapq %rax
; CHECK-NEXT:    movq %rax, %rsi
; CHECK-NEXT:    shrq $4, %rsi
; CHECK-NEXT:    movabsq $1085102592571150095, %r10 # imm = 0xF0F0F0F0F0F0F0F
; CHECK-NEXT:    andq %r10, %rsi
; CHECK-NEXT:    andq %r10, %rax
; CHECK-NEXT:    shlq $4, %rax
; CHECK-NEXT:    orq %rsi, %rax
; CHECK-NEXT:    movabsq $3689348814741910323, %rsi # imm = 0x3333333333333333
; CHECK-NEXT:    movq %rax, %r11
; CHECK-NEXT:    andq %rsi, %r11
; CHECK-NEXT:    shrq $2, %rax
; CHECK-NEXT:    andq %rsi, %rax
; CHECK-NEXT:    leaq (%rax,%r11,4), %rax
; CHECK-NEXT:    movabsq $6148914691236517205, %r11 # imm = 0x5555555555555555
; CHECK-NEXT:    movq %rax, %r15
; CHECK-NEXT:    andq %r11, %r15
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    andq %r11, %rax
; CHECK-NEXT:    leaq (%rax,%r15,2), %r15
; CHECK-NEXT:    bswapq %r12
; CHECK-NEXT:    movq %r12, %rax
; CHECK-NEXT:    shrq $4, %rax
; CHECK-NEXT:    andq %r10, %rax
; CHECK-NEXT:    andq %r10, %r12
; CHECK-NEXT:    shlq $4, %r12
; CHECK-NEXT:    orq %rax, %r12
; CHECK-NEXT:    movq %r12, %rax
; CHECK-NEXT:    andq %rsi, %rax
; CHECK-NEXT:    shrq $2, %r12
; CHECK-NEXT:    andq %rsi, %r12
; CHECK-NEXT:    leaq (%r12,%rax,4), %rax
; CHECK-NEXT:    movabsq $6148914691230924800, %r12 # imm = 0x5555555555000000
; CHECK-NEXT:    movq %rax, %rbp
; CHECK-NEXT:    andq %r12, %rbp
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    andq %r12, %rax
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %r12
; CHECK-NEXT:    leaq (%rax,%rbp,2), %rax
; CHECK-NEXT:    shrdq $24, %r15, %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    bswapq %r12
; CHECK-NEXT:    movq %r12, %rax
; CHECK-NEXT:    shrq $4, %rax
; CHECK-NEXT:    andq %r10, %rax
; CHECK-NEXT:    andq %r10, %r12
; CHECK-NEXT:    shlq $4, %r12
; CHECK-NEXT:    orq %rax, %r12
; CHECK-NEXT:    movq %r12, %rax
; CHECK-NEXT:    andq %rsi, %rax
; CHECK-NEXT:    shrq $2, %r12
; CHECK-NEXT:    andq %rsi, %r12
; CHECK-NEXT:    leaq (%r12,%rax,4), %rax
; CHECK-NEXT:    movq %rax, %r12
; CHECK-NEXT:    andq %r11, %r12
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    andq %r11, %rax
; CHECK-NEXT:    leaq (%rax,%r12,2), %r12
; CHECK-NEXT:    movq %r12, %rax
; CHECK-NEXT:    shldq $40, %r15, %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    bswapq %r14
; CHECK-NEXT:    movq %r14, %rax
; CHECK-NEXT:    shrq $4, %rax
; CHECK-NEXT:    andq %r10, %rax
; CHECK-NEXT:    andq %r10, %r14
; CHECK-NEXT:    shlq $4, %r14
; CHECK-NEXT:    orq %rax, %r14
; CHECK-NEXT:    movq %r14, %rax
; CHECK-NEXT:    andq %rsi, %rax
; CHECK-NEXT:    shrq $2, %r14
; CHECK-NEXT:    andq %rsi, %r14
; CHECK-NEXT:    leaq (%r14,%rax,4), %rax
; CHECK-NEXT:    movq %rax, %r14
; CHECK-NEXT:    andq %r11, %r14
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    andq %r11, %rax
; CHECK-NEXT:    leaq (%rax,%r14,2), %rax
; CHECK-NEXT:    shrdq $24, %rax, %r12
; CHECK-NEXT:    movq %r12, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    bswapq %rbx
; CHECK-NEXT:    movq %rbx, %r14
; CHECK-NEXT:    shrq $4, %r14
; CHECK-NEXT:    andq %r10, %r14
; CHECK-NEXT:    andq %r10, %rbx
; CHECK-NEXT:    shlq $4, %rbx
; CHECK-NEXT:    orq %r14, %rbx
; CHECK-NEXT:    movq %rbx, %r14
; CHECK-NEXT:    andq %rsi, %r14
; CHECK-NEXT:    shrq $2, %rbx
; CHECK-NEXT:    andq %rsi, %rbx
; CHECK-NEXT:    leaq (%rbx,%r14,4), %rbx
; CHECK-NEXT:    movq %rbx, %r14
; CHECK-NEXT:    andq %r11, %r14
; CHECK-NEXT:    shrq %rbx
; CHECK-NEXT:    andq %r11, %rbx
; CHECK-NEXT:    leaq (%rbx,%r14,2), %r14
; CHECK-NEXT:    movq %r14, %rbx
; CHECK-NEXT:    movq %r14, %r15
; CHECK-NEXT:    shldq $40, %rax, %rbx
; CHECK-NEXT:    movq %rbx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rax
; CHECK-NEXT:    bswapq %rax
; CHECK-NEXT:    movq %rax, %rbx
; CHECK-NEXT:    shrq $4, %rbx
; CHECK-NEXT:    andq %r10, %rbx
; CHECK-NEXT:    andq %r10, %rax
; CHECK-NEXT:    shlq $4, %rax
; CHECK-NEXT:    orq %rbx, %rax
; CHECK-NEXT:    movq %rax, %rbx
; CHECK-NEXT:    andq %rsi, %rbx
; CHECK-NEXT:    shrq $2, %rax
; CHECK-NEXT:    andq %rsi, %rax
; CHECK-NEXT:    leaq (%rax,%rbx,4), %rax
; CHECK-NEXT:    movq %rax, %rbx
; CHECK-NEXT:    andq %r11, %rbx
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    andq %r11, %rax
; CHECK-NEXT:    leaq (%rax,%rbx,2), %rbx
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rax
; CHECK-NEXT:    bswapq %rax
; CHECK-NEXT:    movq %rax, %r14
; CHECK-NEXT:    shrq $4, %r14
; CHECK-NEXT:    andq %r10, %r14
; CHECK-NEXT:    andq %r10, %rax
; CHECK-NEXT:    shlq $4, %rax
; CHECK-NEXT:    orq %r14, %rax
; CHECK-NEXT:    movq %rax, %r14
; CHECK-NEXT:    andq %rsi, %r14
; CHECK-NEXT:    shrq $2, %rax
; CHECK-NEXT:    andq %rsi, %rax
; CHECK-NEXT:    leaq (%rax,%r14,4), %rax
; CHECK-NEXT:    movq %rax, %r14
; CHECK-NEXT:    andq %r11, %r14
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    andq %r11, %rax
; CHECK-NEXT:    leaq (%rax,%r14,2), %rbp
; CHECK-NEXT:    shrdq $24, %rbx, %r15
; CHECK-NEXT:    movq %r15, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movq %rbp, %rax
; CHECK-NEXT:    shldq $40, %rbx, %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rax
; CHECK-NEXT:    bswapq %rax
; CHECK-NEXT:    movq %rax, %rbx
; CHECK-NEXT:    shrq $4, %rbx
; CHECK-NEXT:    andq %r10, %rbx
; CHECK-NEXT:    andq %r10, %rax
; CHECK-NEXT:    shlq $4, %rax
; CHECK-NEXT:    orq %rbx, %rax
; CHECK-NEXT:    movq %rax, %rbx
; CHECK-NEXT:    andq %rsi, %rbx
; CHECK-NEXT:    shrq $2, %rax
; CHECK-NEXT:    andq %rsi, %rax
; CHECK-NEXT:    leaq (%rax,%rbx,4), %rax
; CHECK-NEXT:    movq %rax, %rbx
; CHECK-NEXT:    andq %r11, %rbx
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    andq %r11, %rax
; CHECK-NEXT:    leaq (%rax,%rbx,2), %rbx
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rax
; CHECK-NEXT:    bswapq %rax
; CHECK-NEXT:    movq %rax, %r14
; CHECK-NEXT:    shrq $4, %r14
; CHECK-NEXT:    andq %r10, %r14
; CHECK-NEXT:    andq %r10, %rax
; CHECK-NEXT:    shlq $4, %rax
; CHECK-NEXT:    orq %r14, %rax
; CHECK-NEXT:    movq %rax, %r14
; CHECK-NEXT:    andq %rsi, %r14
; CHECK-NEXT:    shrq $2, %rax
; CHECK-NEXT:    andq %rsi, %rax
; CHECK-NEXT:    leaq (%rax,%r14,4), %rax
; CHECK-NEXT:    movq %rax, %r14
; CHECK-NEXT:    andq %r11, %r14
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    andq %r11, %rax
; CHECK-NEXT:    leaq (%rax,%r14,2), %r15
; CHECK-NEXT:    shrdq $24, %rbx, %rbp
; CHECK-NEXT:    movq %r15, %r12
; CHECK-NEXT:    shldq $40, %rbx, %r12
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rax
; CHECK-NEXT:    bswapq %rax
; CHECK-NEXT:    movq %rax, %rbx
; CHECK-NEXT:    shrq $4, %rbx
; CHECK-NEXT:    andq %r10, %rbx
; CHECK-NEXT:    andq %r10, %rax
; CHECK-NEXT:    shlq $4, %rax
; CHECK-NEXT:    orq %rbx, %rax
; CHECK-NEXT:    movq %rax, %rbx
; CHECK-NEXT:    andq %rsi, %rbx
; CHECK-NEXT:    shrq $2, %rax
; CHECK-NEXT:    andq %rsi, %rax
; CHECK-NEXT:    leaq (%rax,%rbx,4), %rax
; CHECK-NEXT:    movq %rax, %rbx
; CHECK-NEXT:    andq %r11, %rbx
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    andq %r11, %rax
; CHECK-NEXT:    leaq (%rax,%rbx,2), %rax
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rbx
; CHECK-NEXT:    bswapq %rbx
; CHECK-NEXT:    movq %rbx, %r14
; CHECK-NEXT:    shrq $4, %r14
; CHECK-NEXT:    andq %r10, %r14
; CHECK-NEXT:    andq %r10, %rbx
; CHECK-NEXT:    shlq $4, %rbx
; CHECK-NEXT:    orq %r14, %rbx
; CHECK-NEXT:    movq %rbx, %r14
; CHECK-NEXT:    andq %rsi, %r14
; CHECK-NEXT:    shrq $2, %rbx
; CHECK-NEXT:    andq %rsi, %rbx
; CHECK-NEXT:    leaq (%rbx,%r14,4), %rbx
; CHECK-NEXT:    movq %rbx, %r14
; CHECK-NEXT:    andq %r11, %r14
; CHECK-NEXT:    shrq %rbx
; CHECK-NEXT:    andq %r11, %rbx
; CHECK-NEXT:    leaq (%rbx,%r14,2), %rbx
; CHECK-NEXT:    shrdq $24, %rax, %r15
; CHECK-NEXT:    movq %rbx, %r14
; CHECK-NEXT:    shldq $40, %rax, %r14
; CHECK-NEXT:    bswapq %r9
; CHECK-NEXT:    movq %r9, %rax
; CHECK-NEXT:    shrq $4, %rax
; CHECK-NEXT:    andq %r10, %rax
; CHECK-NEXT:    andq %r10, %r9
; CHECK-NEXT:    shlq $4, %r9
; CHECK-NEXT:    orq %rax, %r9
; CHECK-NEXT:    movq %r9, %rax
; CHECK-NEXT:    andq %rsi, %rax
; CHECK-NEXT:    shrq $2, %r9
; CHECK-NEXT:    andq %rsi, %r9
; CHECK-NEXT:    leaq (%r9,%rax,4), %rax
; CHECK-NEXT:    movq %rax, %r9
; CHECK-NEXT:    andq %r11, %r9
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    andq %r11, %rax
; CHECK-NEXT:    leaq (%rax,%r9,2), %rax
; CHECK-NEXT:    bswapq %r8
; CHECK-NEXT:    movq %r8, %r9
; CHECK-NEXT:    shrq $4, %r9
; CHECK-NEXT:    andq %r10, %r9
; CHECK-NEXT:    andq %r10, %r8
; CHECK-NEXT:    shlq $4, %r8
; CHECK-NEXT:    orq %r9, %r8
; CHECK-NEXT:    movq %r8, %r9
; CHECK-NEXT:    andq %rsi, %r9
; CHECK-NEXT:    shrq $2, %r8
; CHECK-NEXT:    andq %rsi, %r8
; CHECK-NEXT:    leaq (%r8,%r9,4), %r8
; CHECK-NEXT:    movq %r8, %r9
; CHECK-NEXT:    andq %r11, %r9
; CHECK-NEXT:    shrq %r8
; CHECK-NEXT:    andq %r11, %r8
; CHECK-NEXT:    leaq (%r8,%r9,2), %r8
; CHECK-NEXT:    shrdq $24, %rax, %rbx
; CHECK-NEXT:    movq %r8, %r9
; CHECK-NEXT:    shldq $40, %rax, %r9
; CHECK-NEXT:    bswapq %rcx
; CHECK-NEXT:    movq %rcx, %rax
; CHECK-NEXT:    shrq $4, %rax
; CHECK-NEXT:    andq %r10, %rax
; CHECK-NEXT:    andq %r10, %rcx
; CHECK-NEXT:    shlq $4, %rcx
; CHECK-NEXT:    orq %rax, %rcx
; CHECK-NEXT:    movq %rcx, %rax
; CHECK-NEXT:    andq %rsi, %rax
; CHECK-NEXT:    shrq $2, %rcx
; CHECK-NEXT:    andq %rsi, %rcx
; CHECK-NEXT:    leaq (%rcx,%rax,4), %rax
; CHECK-NEXT:    movq %rax, %rcx
; CHECK-NEXT:    andq %r11, %rcx
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    andq %r11, %rax
; CHECK-NEXT:    leaq (%rax,%rcx,2), %rax
; CHECK-NEXT:    bswapq %rdx
; CHECK-NEXT:    movq %rdx, %rcx
; CHECK-NEXT:    shrq $4, %rcx
; CHECK-NEXT:    andq %r10, %rcx
; CHECK-NEXT:    andq %r10, %rdx
; CHECK-NEXT:    shlq $4, %rdx
; CHECK-NEXT:    orq %rcx, %rdx
; CHECK-NEXT:    movq %rdx, %rcx
; CHECK-NEXT:    andq %rsi, %rcx
; CHECK-NEXT:    shrq $2, %rdx
; CHECK-NEXT:    andq %rsi, %rdx
; CHECK-NEXT:    leaq (%rdx,%rcx,4), %rcx
; CHECK-NEXT:    movq %rcx, %rdx
; CHECK-NEXT:    andq %r11, %rdx
; CHECK-NEXT:    shrq %rcx
; CHECK-NEXT:    andq %r11, %rcx
; CHECK-NEXT:    leaq (%rcx,%rdx,2), %rcx
; CHECK-NEXT:    shrdq $24, %rax, %r8
; CHECK-NEXT:    movq %rcx, %rdx
; CHECK-NEXT:    shldq $40, %rax, %rdx
; CHECK-NEXT:    bswapq %r13
; CHECK-NEXT:    movq %r13, %rax
; CHECK-NEXT:    shrq $4, %rax
; CHECK-NEXT:    andq %r10, %rax
; CHECK-NEXT:    andq %r10, %r13
; CHECK-NEXT:    shlq $4, %r13
; CHECK-NEXT:    orq %rax, %r13
; CHECK-NEXT:    movq %r13, %rax
; CHECK-NEXT:    andq %rsi, %rax
; CHECK-NEXT:    shrq $2, %r13
; CHECK-NEXT:    andq %rsi, %r13
; CHECK-NEXT:    leaq (%r13,%rax,4), %rax
; CHECK-NEXT:    movq %rax, %rsi
; CHECK-NEXT:    andq %r11, %rsi
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    andq %r11, %rax
; CHECK-NEXT:    leaq (%rax,%rsi,2), %rax
; CHECK-NEXT:    shrdq $24, %rax, %rcx
; CHECK-NEXT:    movq %rcx, 112(%rdi)
; CHECK-NEXT:    movq %rdx, 104(%rdi)
; CHECK-NEXT:    movq %r8, 96(%rdi)
; CHECK-NEXT:    movq %r9, 88(%rdi)
; CHECK-NEXT:    movq %rbx, 80(%rdi)
; CHECK-NEXT:    movq %r14, 72(%rdi)
; CHECK-NEXT:    movq %r15, 64(%rdi)
; CHECK-NEXT:    movq %r12, 56(%rdi)
; CHECK-NEXT:    movq %rbp, 48(%rdi)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; CHECK-NEXT:    movq %rcx, 40(%rdi)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; CHECK-NEXT:    movq %rcx, 32(%rdi)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; CHECK-NEXT:    movq %rcx, 24(%rdi)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; CHECK-NEXT:    movq %rcx, 16(%rdi)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; CHECK-NEXT:    movq %rcx, 8(%rdi)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; CHECK-NEXT:    movq %rcx, (%rdi)
; CHECK-NEXT:    movq %rax, %rcx
; CHECK-NEXT:    shrq $56, %rax
; CHECK-NEXT:    movb %al, 124(%rdi)
; CHECK-NEXT:    shrq $24, %rcx
; CHECK-NEXT:    movl %ecx, 120(%rdi)
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    retq
  %Z = call i1000 @llvm.bitreverse.i1000(i1000 %A)
  ret i1000 %Z
}

declare i1000 @llvm.bitreverse.i1000(i1000)
