; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+soft-float | FileCheck %s

define i1 @foo(ptr %x, ptr %y) {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq (%rdi), %rax
; CHECK-NEXT:    movq 8(%rdi), %rcx
; CHECK-NEXT:    movq 8(%rsi), %rdx
; CHECK-NEXT:    xorq %rcx, %rdx
; CHECK-NEXT:    movq (%rsi), %rcx
; CHECK-NEXT:    xorq %rax, %rcx
; CHECK-NEXT:    orq %rcx, %rdx
; CHECK-NEXT:    sete %al
; CHECK-NEXT:    retq
  %a = load i128, ptr %x, align 16
  %b = load i128, ptr %y, align 16
  %c = icmp eq i128 %a, %b
  ret i1 %c
}
