; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --no_x86_scrub_sp --version 2
; RUN: llc -mtriple=x86_64-unknown-linux < %s | FileCheck %s

; Make sure the argument is read before the stack slot is over-written.
define i1 @test(ptr %a0, ptr %a1, ptr %a2, ptr %a3, ptr %a4, ptr %a5, i128 %x) {
; CHECK-LABEL: test:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq 8(%rsp), %rax
; CHECK-NEXT:    xorps %xmm0, %xmm0
; CHECK-NEXT:    movq 16(%rsp), %rcx
; CHECK-NEXT:    andq %rax, %rcx
; CHECK-NEXT:    movaps %xmm0, 8(%rsp)
; CHECK-NEXT:    cmpq $-1, %rcx
; CHECK-NEXT:    sete %al
; CHECK-NEXT:    retq
  %alloca = alloca i128
  store i128 %x, ptr %alloca
  store i128 0, ptr %alloca
  %cmp = icmp eq i128 %x, -1
  ret i1 %cmp
}
