; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown-linux | FileCheck %s

; This test verifies that the experimental.vector.extract.last.active intrinsic
; doesn't cause an infinite loop during legalization when the step vector type
; needs widening (e.g., v4i8 -> v16i8 on X86).

define i32 @extract_last_active_v4i32(<4 x i32> %a, <4 x i1> %c) {
; CHECK-LABEL: extract_last_active_v4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pshufd {{.*#+}} xmm2 = xmm1[3,3,3,3]
; CHECK-NEXT:    movd %xmm2, %ecx
; CHECK-NEXT:    pshufd {{.*#+}} xmm2 = xmm1[2,3,2,3]
; CHECK-NEXT:    movd %xmm2, %eax
; CHECK-NEXT:    movd %xmm1, %edx
; CHECK-NEXT:    pshufd {{.*#+}} xmm2 = xmm1[1,1,1,1]
; CHECK-NEXT:    movd %xmm2, %esi
; CHECK-NEXT:    pslld $31, %xmm1
; CHECK-NEXT:    psrad $31, %xmm1
; CHECK-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movdqa {{.*#+}} xmm0 = [u,1,2,3]
; CHECK-NEXT:    pand %xmm1, %xmm0
; CHECK-NEXT:    pshufd {{.*#+}} xmm1 = xmm0[2,3,2,3]
; CHECK-NEXT:    movd %xmm1, %edi
; CHECK-NEXT:    pshufd {{.*#+}} xmm1 = xmm0[1,1,1,1]
; CHECK-NEXT:    movd %xmm1, %r8d
; CHECK-NEXT:    cmpl %edi, %r8d
; CHECK-NEXT:    cmoval %r8d, %edi
; CHECK-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[3,3,3,3]
; CHECK-NEXT:    movd %xmm0, %r8d
; CHECK-NEXT:    cmpl %r8d, %edi
; CHECK-NEXT:    cmoval %edi, %r8d
; CHECK-NEXT:    orl %edx, %esi
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    orl %esi, %eax
; CHECK-NEXT:    andb $1, %al
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpb $1, %al
; CHECK-NEXT:    sbbl %ecx, %ecx
; CHECK-NEXT:    movl -24(%rsp,%r8,4), %eax
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    retq
  %res = call i32 @llvm.experimental.vector.extract.last.active.v4i32(<4 x i32> %a, <4 x i1> %c, i32 -1)
  ret i32 %res
}

define i32 @extract_last_active_v4i32_no_default(<4 x i32> %a, <4 x i1> %c) {
; CHECK-LABEL: extract_last_active_v4i32_no_default:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pslld $31, %xmm1
; CHECK-NEXT:    psrad $31, %xmm1
; CHECK-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movdqa {{.*#+}} xmm0 = [u,1,2,3]
; CHECK-NEXT:    pand %xmm1, %xmm0
; CHECK-NEXT:    pshufd {{.*#+}} xmm1 = xmm0[2,3,2,3]
; CHECK-NEXT:    movd %xmm1, %eax
; CHECK-NEXT:    pshufd {{.*#+}} xmm1 = xmm0[1,1,1,1]
; CHECK-NEXT:    movd %xmm1, %ecx
; CHECK-NEXT:    cmpl %eax, %ecx
; CHECK-NEXT:    cmoval %ecx, %eax
; CHECK-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[3,3,3,3]
; CHECK-NEXT:    movd %xmm0, %ecx
; CHECK-NEXT:    cmpl %ecx, %eax
; CHECK-NEXT:    cmoval %eax, %ecx
; CHECK-NEXT:    movl -24(%rsp,%rcx,4), %eax
; CHECK-NEXT:    retq
  %res = call i32 @llvm.experimental.vector.extract.last.active.v4i32(<4 x i32> %a, <4 x i1> %c, i32 poison)
  ret i32 %res
}

; Test v2i32 - smaller vector.
define i32 @extract_last_active_v2i32(<2 x i32> %a, <2 x i1> %c) {
; CHECK-LABEL: extract_last_active_v2i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pshufd {{.*#+}} xmm2 = xmm1[2,3,2,3]
; CHECK-NEXT:    movq %xmm1, %rax
; CHECK-NEXT:    psllq $63, %xmm1
; CHECK-NEXT:    movq %xmm2, %rcx
; CHECK-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    orl %eax, %ecx
; CHECK-NEXT:    andb $1, %cl
; CHECK-NEXT:    xorl %edx, %edx
; CHECK-NEXT:    cmpb $1, %cl
; CHECK-NEXT:    sbbl %edx, %edx
; CHECK-NEXT:    pshufd {{.*#+}} xmm0 = xmm1[3,3,3,3]
; CHECK-NEXT:    psrld $31, %xmm0
; CHECK-NEXT:    movq %xmm0, %rax
; CHECK-NEXT:    movl %eax, %eax
; CHECK-NEXT:    movl -24(%rsp,%rax,4), %eax
; CHECK-NEXT:    orl %edx, %eax
; CHECK-NEXT:    retq
  %res = call i32 @llvm.experimental.vector.extract.last.active.v2i32(<2 x i32> %a, <2 x i1> %c, i32 -1)
  ret i32 %res
}

; Test v3i32 - non-power-of-2 element count that requires mask widening
; (v3i1 -> v4i1) via WidenVecOp_VECTOR_FIND_LAST_ACTIVE.
define i32 @extract_last_active_v3i32(<3 x i32> %a, <3 x i1> %c) {
; CHECK-LABEL: extract_last_active_v3i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movd %edx, %xmm0
; CHECK-NEXT:    movd %esi, %xmm1
; CHECK-NEXT:    shufps {{.*#+}} xmm1 = xmm1[1,0],xmm0[0,1]
; CHECK-NEXT:    pslld $31, %xmm1
; CHECK-NEXT:    psrad $31, %xmm1
; CHECK-NEXT:    movdqa {{.*#+}} xmm0 = [u,1,2,3]
; CHECK-NEXT:    pand %xmm1, %xmm0
; CHECK-NEXT:    pshufd {{.*#+}} xmm1 = xmm0[2,3,2,3]
; CHECK-NEXT:    movd %xmm1, %eax
; CHECK-NEXT:    pshufd {{.*#+}} xmm1 = xmm0[1,1,1,1]
; CHECK-NEXT:    movd %xmm1, %ecx
; CHECK-NEXT:    cmpl %eax, %ecx
; CHECK-NEXT:    cmoval %ecx, %eax
; CHECK-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[3,3,3,3]
; CHECK-NEXT:    movd %xmm0, %ecx
; CHECK-NEXT:    cmpl %ecx, %eax
; CHECK-NEXT:    cmoval %eax, %ecx
; CHECK-NEXT:    orl %esi, %edi
; CHECK-NEXT:    orl %edx, %edi
; CHECK-NEXT:    andb $1, %dil
; CHECK-NEXT:    xorl %edx, %edx
; CHECK-NEXT:    cmpb $1, %dil
; CHECK-NEXT:    sbbl %edx, %edx
; CHECK-NEXT:    movl -24(%rsp,%rcx,4), %eax
; CHECK-NEXT:    orl %edx, %eax
; CHECK-NEXT:    retq
  %res = call i32 @llvm.experimental.vector.extract.last.active.v3i32(<3 x i32> %a, <3 x i1> %c, i32 -1)
  ret i32 %res
}

; Test v8i32 - larger vector where step vector type doesn't need widening.
define i32 @extract_last_active_v8i32(<8 x i32> %a, <8 x i1> %c) {
; CHECK-LABEL: extract_last_active_v8i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset %rbx, -16
; CHECK-NEXT:    pextrw $7, %xmm2, %eax
; CHECK-NEXT:    pextrw $6, %xmm2, %edx
; CHECK-NEXT:    pextrw $5, %xmm2, %edi
; CHECK-NEXT:    pextrw $4, %xmm2, %ecx
; CHECK-NEXT:    pextrw $3, %xmm2, %r8d
; CHECK-NEXT:    pextrw $2, %xmm2, %esi
; CHECK-NEXT:    pextrw $1, %xmm2, %r9d
; CHECK-NEXT:    movd %xmm2, %r10d
; CHECK-NEXT:    psllw $15, %xmm2
; CHECK-NEXT:    psraw $15, %xmm2
; CHECK-NEXT:    movaps %xmm1, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movdqa {{.*#+}} xmm0 = [u,1,2,3,4,5,6,7]
; CHECK-NEXT:    pand %xmm2, %xmm0
; CHECK-NEXT:    pextrw $2, %xmm0, %r11d
; CHECK-NEXT:    pextrw $1, %xmm0, %ebx
; CHECK-NEXT:    cmpw %r11w, %bx
; CHECK-NEXT:    cmoval %ebx, %r11d
; CHECK-NEXT:    pextrw $3, %xmm0, %ebx
; CHECK-NEXT:    cmpw %bx, %r11w
; CHECK-NEXT:    cmoval %r11d, %ebx
; CHECK-NEXT:    pextrw $4, %xmm0, %r11d
; CHECK-NEXT:    cmpw %r11w, %bx
; CHECK-NEXT:    cmoval %ebx, %r11d
; CHECK-NEXT:    pextrw $5, %xmm0, %ebx
; CHECK-NEXT:    cmpw %bx, %r11w
; CHECK-NEXT:    cmoval %r11d, %ebx
; CHECK-NEXT:    pextrw $6, %xmm0, %r11d
; CHECK-NEXT:    cmpw %r11w, %bx
; CHECK-NEXT:    cmoval %ebx, %r11d
; CHECK-NEXT:    pextrw $7, %xmm0, %ebx
; CHECK-NEXT:    cmpw %bx, %r11w
; CHECK-NEXT:    cmoval %r11d, %ebx
; CHECK-NEXT:    andl $7, %ebx
; CHECK-NEXT:    orl %r10d, %r9d
; CHECK-NEXT:    orl %r8d, %esi
; CHECK-NEXT:    orl %r9d, %esi
; CHECK-NEXT:    orl %edi, %ecx
; CHECK-NEXT:    orl %edx, %ecx
; CHECK-NEXT:    orl %esi, %ecx
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    andb $1, %al
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpb $1, %al
; CHECK-NEXT:    sbbl %ecx, %ecx
; CHECK-NEXT:    movl -32(%rsp,%rbx,4), %eax
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %res = call i32 @llvm.experimental.vector.extract.last.active.v8i32(<8 x i32> %a, <8 x i1> %c, i32 -1)
  ret i32 %res
}

; Test v16i32 - even larger vector.
define i32 @extract_last_active_v16i32(<16 x i32> %a, <16 x i1> %c) {
; CHECK-LABEL: extract_last_active_v16i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movdqa %xmm4, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    psllw $7, %xmm4
; CHECK-NEXT:    pxor %xmm5, %xmm5
; CHECK-NEXT:    pcmpgtb %xmm4, %xmm5
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    movdqa {{.*#+}} xmm4 = [u,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
; CHECK-NEXT:    pand %xmm5, %xmm4
; CHECK-NEXT:    movdqa %xmm4, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movaps %xmm3, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movaps %xmm2, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movaps %xmm1, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %cl, %dl
; CHECK-NEXT:    cmoval %edx, %ecx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %dl, %cl
; CHECK-NEXT:    cmoval %ecx, %edx
; CHECK-NEXT:    movl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    cmpb %sil, %dl
; CHECK-NEXT:    cmoval %edx, %esi
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %dl, %sil
; CHECK-NEXT:    cmoval %esi, %edx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    cmpb %sil, %dl
; CHECK-NEXT:    cmoval %edx, %esi
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %dl, %sil
; CHECK-NEXT:    cmoval %esi, %edx
; CHECK-NEXT:    cmpb %cl, %dl
; CHECK-NEXT:    cmoval %edx, %ecx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %dl, %cl
; CHECK-NEXT:    cmoval %ecx, %edx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    cmpb %cl, %dl
; CHECK-NEXT:    cmoval %edx, %ecx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %dl, %cl
; CHECK-NEXT:    cmoval %ecx, %edx
; CHECK-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    cmpb %cl, %dl
; CHECK-NEXT:    cmoval %edx, %ecx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %dl, %cl
; CHECK-NEXT:    cmoval %ecx, %edx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    cmpb %sil, %dl
; CHECK-NEXT:    cmoval %edx, %esi
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    cmpb %cl, %sil
; CHECK-NEXT:    cmoval %esi, %ecx
; CHECK-NEXT:    andl $15, %ecx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    orb %al, %dl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    orb %dl, %al
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    orb %al, %dl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    orb %dl, %al
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    orb %al, %dl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    orb %dl, %al
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    orb %al, %dl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    orb %dl, %al
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    orb %al, %dl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    orb %dl, %al
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    orb %al, %dl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    orb %dl, %al
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    orb %al, %dl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    orb %dl, %al
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    orb %al, %dl
; CHECK-NEXT:    andb $1, %dl
; CHECK-NEXT:    xorl %esi, %esi
; CHECK-NEXT:    cmpb $1, %dl
; CHECK-NEXT:    sbbl %esi, %esi
; CHECK-NEXT:    movl -72(%rsp,%rcx,4), %eax
; CHECK-NEXT:    orl %esi, %eax
; CHECK-NEXT:    retq
  %res = call i32 @llvm.experimental.vector.extract.last.active.v16i32(<16 x i32> %a, <16 x i1> %c, i32 -1)
  ret i32 %res
}

; Test for older x86 CPUs (pre-AVX) where the mask type legalization creates
; larger element types, requiring the step vector type adjustment.
define i32 @extract_last_active_v4i32_penryn(<4 x i32> %a, <4 x i1> %c) "target-cpu"="penryn" {
; CHECK-LABEL: extract_last_active_v4i32_penryn:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pslld $31, %xmm1
; CHECK-NEXT:    psrad $31, %xmm1
; CHECK-NEXT:    movdqa {{.*#+}} xmm2 = [u,1,2,3]
; CHECK-NEXT:    pand %xmm1, %xmm2
; CHECK-NEXT:    pextrd $2, %xmm2, %eax
; CHECK-NEXT:    pextrd $1, %xmm2, %ecx
; CHECK-NEXT:    cmpl %eax, %ecx
; CHECK-NEXT:    cmoval %ecx, %eax
; CHECK-NEXT:    pextrd $3, %xmm2, %ecx
; CHECK-NEXT:    cmpl %ecx, %eax
; CHECK-NEXT:    cmoval %eax, %ecx
; CHECK-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movl -24(%rsp,%rcx,4), %eax
; CHECK-NEXT:    retq
  %res = call i32 @llvm.experimental.vector.extract.last.active.v4i32(<4 x i32> %a, <4 x i1> %c, i32 poison)
  ret i32 %res
}

define i8 @extract_last_active_split(<32 x i8> %data, <32 x i8> %mask, i8 %passthru) {
; CHECK-LABEL: extract_last_active_split:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pxor %xmm4, %xmm4
; CHECK-NEXT:    movdqa %xmm2, %xmm5
; CHECK-NEXT:    por %xmm3, %xmm5
; CHECK-NEXT:    pcmpeqb %xmm4, %xmm3
; CHECK-NEXT:    pcmpeqd %xmm6, %xmm6
; CHECK-NEXT:    movdqa %xmm3, %xmm7
; CHECK-NEXT:    pxor %xmm6, %xmm7
; CHECK-NEXT:    movdqa %xmm7, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    pcmpeqb %xmm4, %xmm2
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    movdqa {{.*#+}} xmm7 = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
; CHECK-NEXT:    pandn %xmm7, %xmm2
; CHECK-NEXT:    movdqa %xmm2, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    pandn %xmm7, %xmm3
; CHECK-NEXT:    movdqa %xmm3, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movaps %xmm1, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    pcmpeqb %xmm4, %xmm5
; CHECK-NEXT:    pxor %xmm6, %xmm5
; CHECK-NEXT:    movdqa %xmm5, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %cl, %dl
; CHECK-NEXT:    cmoval %edx, %ecx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %dl, %cl
; CHECK-NEXT:    cmoval %ecx, %edx
; CHECK-NEXT:    movl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    cmpb %sil, %dl
; CHECK-NEXT:    cmoval %edx, %esi
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %dl, %sil
; CHECK-NEXT:    cmoval %esi, %edx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    cmpb %sil, %dl
; CHECK-NEXT:    cmoval %edx, %esi
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %dl, %sil
; CHECK-NEXT:    cmoval %esi, %edx
; CHECK-NEXT:    cmpb %cl, %dl
; CHECK-NEXT:    cmoval %edx, %ecx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %dl, %cl
; CHECK-NEXT:    cmoval %ecx, %edx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    cmpb %cl, %dl
; CHECK-NEXT:    cmoval %edx, %ecx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %dl, %cl
; CHECK-NEXT:    cmoval %ecx, %edx
; CHECK-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    cmpb %cl, %dl
; CHECK-NEXT:    cmoval %edx, %ecx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %dl, %cl
; CHECK-NEXT:    cmoval %ecx, %edx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    cmpb %sil, %dl
; CHECK-NEXT:    cmoval %edx, %esi
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    cmpb %cl, %sil
; CHECK-NEXT:    cmoval %esi, %ecx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    cmpb %dl, %sil
; CHECK-NEXT:    cmoval %esi, %edx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    cmpb %sil, %dl
; CHECK-NEXT:    cmoval %edx, %esi
; CHECK-NEXT:    movl -{{[0-9]+}}(%rsp), %r8d
; CHECK-NEXT:    movl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %r8b, %sil
; CHECK-NEXT:    cmoval %esi, %r8d
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    cmpb %sil, %r8b
; CHECK-NEXT:    cmoval %r8d, %esi
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %r8d
; CHECK-NEXT:    cmpb %r8b, %sil
; CHECK-NEXT:    cmoval %esi, %r8d
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    cmpb %sil, %r8b
; CHECK-NEXT:    cmoval %r8d, %esi
; CHECK-NEXT:    cmpb %dl, %sil
; CHECK-NEXT:    cmoval %esi, %edx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    cmpb %sil, %dl
; CHECK-NEXT:    cmoval %edx, %esi
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %dl, %sil
; CHECK-NEXT:    cmoval %esi, %edx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    cmpb %sil, %dl
; CHECK-NEXT:    cmoval %edx, %esi
; CHECK-NEXT:    movl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %dl, %sil
; CHECK-NEXT:    cmoval %esi, %edx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    cmpb %sil, %dl
; CHECK-NEXT:    cmoval %edx, %esi
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    cmpb %dl, %sil
; CHECK-NEXT:    cmoval %esi, %edx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    cmpb %sil, %dl
; CHECK-NEXT:    cmoval %edx, %esi
; CHECK-NEXT:    leal 16(%rsi), %edx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    orb %al, %sil
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    orb %sil, %al
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    orb %al, %sil
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    orb %sil, %al
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    orb %al, %sil
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    orb %sil, %al
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    orb %al, %sil
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    orb %sil, %al
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    orb %al, %sil
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    orb %sil, %al
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    orb %al, %sil
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    orb %sil, %al
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    orb %al, %sil
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    orb %sil, %al
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    orb %al, %sil
; CHECK-NEXT:    testb $1, %sil
; CHECK-NEXT:    cmoveq %rcx, %rdx
; CHECK-NEXT:    andl $31, %edx
; CHECK-NEXT:    movzbl -40(%rsp,%rdx), %eax
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    orb %cl, %dl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    orb %dl, %cl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    orb %cl, %dl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    orb %dl, %cl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    orb %cl, %dl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    orb %dl, %cl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    orb %cl, %dl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    orb %dl, %cl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    orb %cl, %dl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    orb %dl, %cl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    orb %cl, %dl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    orb %dl, %cl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    orb %cl, %dl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    orb %dl, %cl
; CHECK-NEXT:    movzbl -{{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    orb %cl, %dl
; CHECK-NEXT:    testb $1, %dl
; CHECK-NEXT:    cmovel %edi, %eax
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retq
  %notzero = icmp ne <32 x i8> %mask, zeroinitializer
  %res = call i8 @llvm.experimental.vector.extract.last.active.v16i8(<32 x i8> %data, <32 x i1> %notzero, i8 %passthru)
  ret i8 %res
}
